# Week 5 Lab Notebook #1: PyTorch Basics
## Building Blocks for Neural Networks

### Learning Objectives
By the end of this notebook, you will:
- Understand what PyTorch is and why we use it
- Create and manipulate tensors (the fundamental data structure)
- Perform basic operations needed for neural networks
- Understand how PyTorch handles automatic differentiation

---

## Part 1: What is PyTorch?

**PyTorch** is a Python library that helps us build neural networks. Think of it as:
- **NumPy** (for arrays) + **Automatic differentiation** (for learning) + **GPU support** (for speed)

### Why PyTorch?
1. **Easy to learn**: If you know Python and NumPy, PyTorch feels natural
2. **Dynamic**: You can change your network on the fly (great for experimenting)
3. **Popular**: Lots of tutorials, examples, and community support

Let's start by importing PyTorch and checking our setup:

In [8]:
# Import PyTorch
import torch
import numpy as np

# Check PyTorch version
print(f"PyTorch version: {torch.__version__}")

# Check if GPU is available (don't worry if it says False if you are a Mac user)
print(f"GPU available: {torch.cuda.is_available()}")
print("\n✓ PyTorch is ready to use.")

PyTorch version: 2.5.1
GPU available: False

✓ PyTorch is ready to use.


---

## Part 2: Tensors - The Building Blocks

### What are Tensors?
Tensors are just **multi-dimensional arrays**, like NumPy arrays but with superpowers:
- They can run on GPUs (much faster for large computations)
- They can automatically calculate gradients (essential for training)

### Tensor Dimensions:
- **Scalar** (0D): Just a number
- **Vector** (1D): A list of numbers [1, 2, 3, 4]
- **Matrix** (2D): A grid of numbers (like an image)
- **3D Tensor**: A cube of numbers (like a color image: height × width × channels)
- **4D Tensor**: Multiple 3D tensors (like a batch of images)

### Creating Tensors

Let's create some tensors and see what they look like:

In [4]:
# Method 1: Create from Python lists
# Scalar (0D tensor)
scalar = torch.tensor(42) 
print("Scalar:")
print(f"Value: {scalar}")
print(f"Shape: {scalar.shape}")
print(f"Dimensions: {scalar.dim()}D\n")

# Vector (1D tensor)
vector = torch.tensor([1, 2, 3, 4])
print("Vector:")
print(f"Value: {vector}")
print(f"Shape: {vector.shape}")
print(f"Dimensions: {vector.dim()}D\n")

# Matrix (2D tensor)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("Matrix:")
print(f"Value:\n{matrix}")
print(f"Shape: {matrix.shape}")
print(f"Dimensions: {matrix.dim()}D")

Scalar:
Value: 42
Shape: torch.Size([])
Dimensions: 0D

Vector:
Value: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Dimensions: 1D

Matrix:
Value:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2D


In [19]:
# Method 2: Create with specific patterns (very useful!)

# Zeros (often used for initialization)
zeros = torch.zeros(3, 4)  # 3 rows, 4 columns
print("Zeros matrix (3x4):")
print(zeros)
print()

# Ones
ones = torch.ones(2, 3)
print("Ones matrix (2x3):")
print(ones)
print()

# Random values (between 0 and 1)
random_tensor = torch.rand(2, 3)
print("Random values:")
print(random_tensor)

Zeros matrix (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones matrix (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random values:
tensor([[0.3423, 0.8334, 0.2887],
        [0.0817, 0.2621, 0.1553]])


### Your Turn: Exercise 2.1
Create the following tensors:
1. A 1D tensor with values [10, 20, 30, 40, 50]
2. A 2D tensor of zeros with shape (5, 5)
3. A 3D tensor of random values with shape (2, 3, 4)

In [21]:
# Your code here:
# 1. Create 1D tensor
my_1d = torch.tensor([10, 20, 30, 40, 50])

# 2. Create 5x5 zeros
my_zeros = torch.zeros(5,5)

# 3. Create 3D random tensor  
my_3d = torch.rand(2, 3, 4)

# Test your tensors
print(f"1D tensor: {my_1d}")
print(f"Zeros shape: {my_zeros.shape}")
print(f"3D tensor shape: {my_3d.shape}")

print(my_1d)
print(my_zeros)
print(my_3d)

1D tensor: tensor([10, 20, 30, 40, 50])
Zeros shape: torch.Size([5, 5])
3D tensor shape: torch.Size([2, 3, 4])
tensor([10, 20, 30, 40, 50])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[[0.2487, 0.3803, 0.3704, 0.4495],
         [0.6129, 0.0983, 0.6273, 0.9004],
         [0.9207, 0.6091, 0.7962, 0.7368]],

        [[0.3036, 0.4139, 0.8476, 0.6971],
         [0.2120, 0.2295, 0.2122, 0.3306],
         [0.7262, 0.0366, 0.5217, 0.3519]]])


---

## Part 3: Tensor Operations

Neural networks are basically lots of mathematical operations on tensors. Let's learn the essential ones:

### Basic Arithmetic

In [27]:
# Create two tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([10, 20, 30, 40])

print("Tensor a:", a)
print("Tensor b:", b)

# Addition
c = a + b
print("a + b =", c)

# Multiplication (element-wise)
d = a * b
print("a * b =", d)

# Scalar operations
e = a * 2
print("a * 2 =", e)

# Mean (average)
print(f"Mean of a: {a.to(torch.float32).mean()}")
print(f"Mean of b: {b.to(torch.float32).mean()}") 
#making tensors floats here instead of when making tensors so no decimals in the outputs


Tensor a: tensor([1, 2, 3, 4])
Tensor b: tensor([10, 20, 30, 40])
a + b = tensor([11, 22, 33, 44])
a * b = tensor([ 10,  40,  90, 160])
a * 2 = tensor([2, 4, 6, 8])
Mean of a: 2.5
Mean of b: 25.0


### Reshaping Tensors

Reshaping is crucial for neural networks. For example, we often need to:
- Flatten images into vectors
- Reshape outputs to match expected dimensions

In [33]:
# Create a 2x3 matrix
matrix = torch.rand(2, 3)
print("Original matrix (2x3):")
print(matrix)

# Reshape to 3x2
reshaped = matrix.reshape(3, 2)
print("Reshaped to 3x2:")
print(reshaped)


# Flatten to 1D (very common for neural networks!)
flattened = matrix.flatten()
print("Flattened to 1D:")
print(flattened)

Original matrix (2x3):
tensor([[0.7677, 0.4243, 0.3711],
        [0.1989, 0.7467, 0.1140]])
Reshaped to 3x2:
tensor([[0.7677, 0.4243],
        [0.3711, 0.1989],
        [0.7467, 0.1140]])
Flattened to 1D:
tensor([0.7677, 0.4243, 0.3711, 0.1989, 0.7467, 0.1140])


### Matrix Multiplication

Matrix multiplication is the core operation in neural networks. It's how layers transform data!

In [12]:
# Matrix multiplication example
# Think of this as: input data @ weights = output

# Input data (2 samples, 3 features each)
input_data = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0]])

# Weights (3 inputs, 2 outputs)
weights = torch.tensor([[0.1, 0.2],
                        [0.3, 0.4],
                        [0.5, 0.6]])

# Matrix multiplication
output = input_data @ weights  # @ is matrix multiplication

print("Input shape:", input_data.shape)
print("Weights shape:", weights.shape)
print("Output shape:", output.shape)
print("\nOutput:")
print(output)

Input shape: torch.Size([2, 3])
Weights shape: torch.Size([3, 2])
Output shape: torch.Size([2, 2])

Output:
tensor([[2.2000, 2.8000],
        [4.9000, 6.4000]])


### 🎯 Your Turn: Exercise 3.1
1. Create two 2x2 matrices with any values
2. Add them together
3. Multiply them element-wise
4. Perform matrix multiplication

In [15]:
# Your code here:
# Create two 2x2 matrices
mat1 = torch.tensor([[1, 2],
                     [4, 5]])
mat2 = torch.tensor([[3, 6],
                     [8, 9]])

# Operations 
add_result = mat1 + mat2
mult_result = mat1 * mat2
matmul_result = mat1 @ mat2

print("Addition:")
print(add_result)
print("\nElement-wise multiplication:")
print(mult_result)
print("\nMatrix multiplication:")
print(matmul_result)

Addition:
tensor([[ 4,  8],
        [12, 14]])

Element-wise multiplication:
tensor([[ 3, 12],
        [32, 45]])

Matrix multiplication:
tensor([[19, 24],
        [52, 69]])


---

## Part 4: Automatic Differentiation (Gradients)

This is PyTorch's superpower! It can automatically calculate gradients (derivatives), which is how neural networks learn.

### Why do we need gradients?
- Neural networks learn by adjusting weights to minimize errors
- Gradients tell us which direction to adjust weights
- PyTorch calculates these automatically!

In [34]:
# Simple example: y = x^2
# We know the derivative is dy/dx = 2x

# Create a tensor with gradient tracking
x = torch.tensor(3.0, requires_grad=True)
print(f"x = {x}")

# Perform operation
y = x ** 2
print(f"y = x^2 = {y}")

# Calculate gradient
y.backward()

# The gradient dy/dx at x=3 should be 2*3 = 6
print(f"\nGradient dy/dx = {x.grad}")
print("Expected: 6.0 (since dy/dx = 2x = 2*3 = 6)")

x = 3.0
y = x^2 = 9.0

Gradient dy/dx = 6.0
Expected: 6.0 (since dy/dx = 2x = 2*3 = 6)


### A More Neural Network-like Example

In [37]:
# Simulate a tiny "neural network" operation
# output = input * weight + bias

# Parameters (what the network will learn)
weight = torch.tensor(0.5, requires_grad=True)
bias = torch.tensor(0.1, requires_grad=True)

# Input data
input_data = torch.tensor(2.0)

# Forward pass
output = input_data * weight + bias
print(f"Input: {input_data}")
print(f"Weight: {weight}")
print(f"Bias: {bias}")
print(f"Output: {output}")

# Pretend this is our "loss" (error)
loss = (output - 3.0) ** 2  # We want output to be 3.0
print(f"\nLoss: {loss}")

# Calculate gradients
loss.backward()

print(f"\nGradients:")
print(f"Weight gradient: {weight.grad}")
print(f"Bias gradient: {bias.grad}")
print("\nThese gradients tell us how to adjust weight and bias to reduce the loss!")

Input: 2.0
Weight: 0.5
Bias: 0.10000000149011612
Output: 1.100000023841858

Loss: 3.609999895095825

Gradients:
Weight gradient: -7.599999904632568
Bias gradient: -3.799999952316284

These gradients tell us how to adjust weight and bias to reduce the loss!


---

## Part 5: Converting Between NumPy and PyTorch

Since we've been using NumPy (with OpenCV), it's useful to know how to convert between NumPy arrays and PyTorch tensors. Be mindful of dtype and device.

In [40]:
# NumPy to PyTorch
numpy_array = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.from_numpy(numpy_array)

print("NumPy array:", numpy_array)
print("PyTorch tensor:", torch_tensor)
print()

# PyTorch to NumPy
tensor = torch.tensor([10, 20, 30, 40])
numpy_from_torch = tensor.numpy()

print("PyTorch tensor:", tensor)
print("NumPy array:", numpy_from_torch)

# Note: They share memory! Changing one changes the other
numpy_from_torch[0] = 999
print("\nAfter changing NumPy array:")
print("NumPy:", numpy_from_torch)
print("Tensor:", tensor)  # Also changed!

NumPy array: [1 2 3 4 5]
PyTorch tensor: tensor([1, 2, 3, 4, 5])

PyTorch tensor: tensor([10, 20, 30, 40])
NumPy array: [10 20 30 40]

After changing NumPy array:
NumPy: [999  20  30  40]
Tensor: tensor([999,  20,  30,  40])


### Your Turn: Exercise 5.1
1. Create a NumPy array representing a 3x3 grayscale image (values 0-255)
2. Convert it to a PyTorch tensor
3. Normalize the values to 0-1 range (divide by 255)
4. Calculate the mean pixel value

In [44]:
# Your code here:
# Create 3x3 "image" as NumPy array
image_np = np.array([[0, 128, 255],
                    [32, 160, 200],
                    [16, 105, 211]])

# Convert to PyTorch
image_tensor = torch.from_numpy(image_np)

# Normalize to 0-1
image_normalized = image_np / 255.0
image_tensornorm = image_tensor.float() / 255.0

# Calculate mean
mean_value = np.mean(image_normalized)
mean_tensor = image_tensornorm.mean().item()

print("Original image (NumPy):")
print(image_np)
print("\nNormalized tensor:")
print(image_normalized)
print(f"\nMean pixel value: {mean_value}")
print("Mean from pytorch:", mean_tensor)

Original image (NumPy):
[[  0 128 255]
 [ 32 160 200]
 [ 16 105 211]]

Normalized tensor:
[[0.         0.50196078 1.        ]
 [0.1254902  0.62745098 0.78431373]
 [0.0627451  0.41176471 0.82745098]]

Mean pixel value: 0.48235294117647054
Mean from pytorch: 0.48235294222831726


---

## Summary

### What You've Learned:
✓ **Tensors** are multi-dimensional arrays (like NumPy but with more features)  
✓ **Creating tensors** from lists, zeros, ones, or random values  
✓ **Operations** like addition, multiplication, and reshaping  
✓ **Automatic gradients** for learning (the magic of neural networks!)  
✓ **Converting** between NumPy and PyTorch  

### Key Takeaways:
1. **Tensors are everywhere** in neural networks - inputs, weights, outputs are all tensors
2. **Reshaping is crucial** - data often needs to be reshaped to flow through networks
3. **Gradients are automatic** - PyTorch handles the calculus for us!

### What's Next:
In the next notebook, we'll use these building blocks to create actual neural network layers!

---

## In-class Assignment 2/4 Part 1/3 (Part of Your Assessment Hand-In)

Create a function that:
1. Takes an image size (height, width) as input
2. Creates a random "image" tensor with values 0-255
3. Applies a simple transformation (e.g., brighten by 20%)
4. Returns both original and transformed tensors

In [9]:
def create_and_transform_image(height, width):
    image_size = (height, width) 
    original = torch.randint(0, 256, image_size, dtype=torch.uint8) #random numbers from 0 to 255
    transformed = original.float() * 1.2 #add 20% brightness to each value in image -- becomes transformed img
    transformed = torch.clamp(transformed, 0, 255).to(torch.uint8)  #clamped so doesn't go above 255 and converted back to uint8
    return original, transformed
    

# Test your function
original, transformed = create_and_transform_image(6, 4)
print("Original:")
print(original)
print("\nTransformed:")
print(transformed)

Original:
tensor([[199,  32, 166,   5],
        [224,  15, 142, 170],
        [150, 184, 111, 253],
        [ 39,  37, 246, 142],
        [ 72,  26, 130, 201],
        [206,  60, 190,  69]], dtype=torch.uint8)

Transformed:
tensor([[238,  38, 199,   6],
        [255,  18, 170, 204],
        [180, 220, 133, 255],
        [ 46,  44, 255, 170],
        [ 86,  31, 156, 241],
        [247,  72, 228,  82]], dtype=torch.uint8)
